CREATE TABLE [dbo].[REQUEST_LOG](
	[ID] [uniqueidentifier] NOT NULL,
	[REQUEST_IP_ADDRESS] [varchar](128) NULL,
	[REQUEST_METHOD] [nvarchar](max) NULL,
	[REQUEST_PATH] [nvarchar](max) NULL,
	[REQUEST_USER_AGENT] [nvarchar](max) NULL,
	[REQUEST_TRACE_IDENTIFIER] [varchar](128) NULL,
	[REQUEST_QUERY_STRING] [nvarchar](max) NULL,
	[REQUEST_BODY] [nvarchar](max) NULL,
	[USER_ID] [numeric](18, 0) NULL,
	[USER_CLAIMS] [nvarchar](max) NULL,
	[TARGET_ID] [numeric](18, 0) NULL,
	[TARGET_OPERATION_TYPE_ID] [numeric](18, 0) NULL,
	[TIMESTAMPE] [time](7) NULL,
 CONSTRAINT [PK_REQUEST_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[REQUEST_LOG] ADD  CONSTRAINT [DF_REQUEST_LOG_ID]  DEFAULT (newid()) FOR [ID]
GO

ALTER TABLE [dbo].[REQUEST_LOG] ADD  CONSTRAINT [DF_REQUEST_LOG_TIMESTAMPE]  DEFAULT (getdate()) FOR [TIMESTAMPE]
GO