CREATE TABLE [dbo].[REQUEST_QUERY_CATEGORY](
	[ID] [bigint] NOT NULL,
	[CATEGORY_NAME] [nvarchar](50) NULL,
	[CATEGORY_PATH] [nvarchar](max) NULL,
	[CATEGORY_PATH_REGEX] [nvarchar](max) NOT NULL,
	[INUSE] [bit] NOT NULL,
	[MODIFIED_DATE] [date] NOT NULL,
 CONSTRAINT [PK_REQUEST_QUERY_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[REQUEST_QUERY_CATEGORY] ADD  CONSTRAINT [DF_REQUEST_QUERY_CATEGORY_INUSE]  DEFAULT ((1)) FOR [INUSE]
GO

ALTER TABLE [dbo].[REQUEST_QUERY_CATEGORY] ADD  CONSTRAINT [DF_REQUEST_QUERY_CATEGORY_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO


INSERT INTO
REQUEST_QUERY_CATEGORY (CATEGORY_NAME, CATEGORY_PATH, CATEGORY_PATH_REGEX)
VALUES ('privacy.read', '/Home/Privacy', '^/Home/Privacy$');

INSERT INTO
REQUEST_QUERY_CATEGORY (CATEGORY_NAME, CATEGORY_PATH, CATEGORY_PATH_REGEX)
VALUES ('test', '/Home/Test', '^/Home/Test/\d+$');